#!/bin/sh

< ~/x11-time.txt tail -n "$((6*60*60))" |
   cut -f2 |
   retitle |
   sort |
   uniq -c |
   sort -n |
   perl -MList::Util=sum -e'
   my @lines = map { chomp; my ($n, $v) = (m/\s+(\d+)\s+(.+)$/); [$n, $v] } <STDIN>;

   my $total = sum(map $_->[0], @lines);

   printf "%d (%d%%) %s\n", $_->[0], 100 * $_->[0] / $total, $_->[1] for @lines;
'
