#!/usr/bin/perl

use warnings;
use strict;

use JSON::PP 'encode_json';

while (<STDIN>) {
   chomp;

   my @v;

   if ($_ eq '') {
         next
   } else {
      @v = ($_);
   }


   print encode_json(\@v) . "\n";
}
