#!/usr/bin/perl

while (<STDIN>) {
   s/Signal.*/Signal/;
   s/#[^ ]+ - Mozilla Firefox/Fun Chat/;
   s/.*"WeeChat.*/IRC Chat/;
   s/^messaging:irc:.*/IRC Chat/;
   s/^messaging:mutt:.*/Personal Email/;
   s/^messaging:zr-(mutt|robbits):.*/ZR Email/;

   # Fun channels
   s/.*(dev-potpourri|random) \| ZipRecruiter Slack - Mozilla Firefox/Fun Chat/;

   # Direct messages
   s/.*\* [^ ]+ \| ZipRecruiter Slack - Mozilla Firefox/Work Chat/;

   # The rest
   s/.* \| ZipRecruiter Slack - Mozilla Firefox/Work Chat/;

   s/.* Google Docs - Mozilla Firefox/ZR Docs/;
   s/.*Google Hangouts - Google Chrome/ZR Meetings/;

   s/.* Google Chrome/Chrome/;
   s/.*Mozilla Firefox/Firefox/;

   if ($_ eq "/bin/zsh\n" || $_ =~ m/^[^:]+:\d+:[^ ]+ - "caliburn"/) {
      next
   }

   s(^[^:]+:[^:]+:.+/unproductive)(Fun Project Unproductive);
   s(^[^:]+:[^:]+:.+/dotfiles)(Fun Project Dotfiles);

   s(^[^:]+:[^:]+:.+/zr)(ZR);
   s(^vim:.+/zr)(ZR);


   print $_;
}
